# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainform.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(878, 254)
        MainWindow.setMinimumSize(QtCore.QSize(878, 254))
        MainWindow.setMaximumSize(QtCore.QSize(878, 254))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.info_imgsave_lb = QtWidgets.QLabel(self.centralwidget)
        self.info_imgsave_lb.setObjectName("info_imgsave_lb")
        self.horizontalLayout_3.addWidget(self.info_imgsave_lb)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.info_save_imagepath_lb = QtWidgets.QLabel(self.centralwidget)
        self.info_save_imagepath_lb.setObjectName("info_save_imagepath_lb")
        self.gridLayout_2.addWidget(self.info_save_imagepath_lb, 0, 0, 1, 1)
        self.info_save_n_lb = QtWidgets.QLabel(self.centralwidget)
        self.info_save_n_lb.setObjectName("info_save_n_lb")
        self.gridLayout_2.addWidget(self.info_save_n_lb, 1, 0, 1, 1)
        self.save_imagepath_input = QtWidgets.QLineEdit(self.centralwidget)
        self.save_imagepath_input.setObjectName("save_imagepath_input")
        self.gridLayout_2.addWidget(self.save_imagepath_input, 0, 1, 1, 1)
        self.save_n_input = QtWidgets.QLineEdit(self.centralwidget)
        self.save_n_input.setObjectName("save_n_input")
        self.gridLayout_2.addWidget(self.save_n_input, 1, 1, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_2)
        self.save_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_btn.setObjectName("save_btn")
        self.verticalLayout_9.addWidget(self.save_btn)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.info_imageload_lb = QtWidgets.QLabel(self.centralwidget)
        self.info_imageload_lb.setObjectName("info_imageload_lb")
        self.horizontalLayout_4.addWidget(self.info_imageload_lb)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.info_load_imagepath_lb = QtWidgets.QLabel(self.centralwidget)
        self.info_load_imagepath_lb.setObjectName("info_load_imagepath_lb")
        self.gridLayout_3.addWidget(self.info_load_imagepath_lb, 0, 0, 1, 1)
        self.load_imagepath_input = QtWidgets.QLineEdit(self.centralwidget)
        self.load_imagepath_input.setObjectName("load_imagepath_input")
        self.gridLayout_3.addWidget(self.load_imagepath_input, 0, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_3)
        self.load_btn = QtWidgets.QPushButton(self.centralwidget)
        self.load_btn.setObjectName("load_btn")
        self.verticalLayout_5.addWidget(self.load_btn)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "클립보드 이미지 메니저"))
        self.info_imgsave_lb.setText(_translate("MainWindow", "    이미지 저장   "))
        self.info_save_imagepath_lb.setText(_translate("MainWindow", "이미지 경로"))
        self.info_save_n_lb.setText(_translate("MainWindow", "n(숫자값)"))
        self.save_btn.setText(_translate("MainWindow", "저장"))
        self.info_imageload_lb.setText(_translate("MainWindow", " 이미지 불러오기"))
        self.info_load_imagepath_lb.setText(_translate("MainWindow", "이미지 경로"))
        self.load_btn.setText(_translate("MainWindow", "불러오기"))

